WITH CTE(ArtistName) AS
	(
		SELECT DISTINCT AN.ArtistName
		FROM
			(
				VALUES
						(N'Marvin Gaye'),
						(N'The Beach Boys'),
						(N'Joni Mitchell'),
						(N'Stevie Wonder'),
						(N'The Beatles'),
						(N'Nirvana'),
						(N'Fleetwood Mac'),
						(N'Prince and the Revolution'),
						(N'Bob Dylan'),
						(N'Lauryn Hill'),
						(N'The Beatles'),
						(N'Michael Jackson'),
						(N'Aretha Franklin'),
						(N'The Rolling Stones'),
						(N'Public Enemy'),
						(N'The Clash'),
						(N'Kanye West'),
						(N'Bob Dylan'),
						(N'Kendrick Lamar'),
						(N'Radiohead'),
						(N'Bruce Springsteen'),
						(N'The Notorious B.I.G.'),
						(N'The Velvet Underground'),
						(N'The Beatles'),
						(N'Carole King'),
						(N'Patti Smith'),
						(N'Wu-Tang Clan'),
						(N'D''Angelo'),
						(N'The Beatles'),
						(N'The Jimi Hendrix Experience'),
						(N'Miles Davis'),
						(N'Beyoncé'),
						(N'Amy Winehouse'),
						(N'Stevie Wonder'),
						(N'The Beatles'),
						(N'Michael Jackson'),
						(N'Dr. Dre'),
						(N'Bob Dylan'),
						(N'Talking Heads'),
						(N'David Bowie'),
						(N'The Rolling Stones'),
						(N'Radiohead'),
						(N'A Tribe Called Quest'),
						(N'Nas'),
						(N'Prince'),
						(N'Paul Simon'),
						(N'Ramones'),
						(N'Bob Marley and the Wailers'),
						(N'Outkast'),
						(N'Jay-Z'),
						(N'Chuck Berry'),
						(N'David Bowie'),
						(N'The Jimi Hendrix Experience'),
						(N'James Brown'),
						(N'Pink Floyd'),
						(N'Liz Phair'),
						(N'The Band'),
						(N'Led Zeppelin'),
						(N'Stevie Wonder'),
						(N'Van Morrison'),
						(N'Eric B. & Rakim'),
						(N'Guns N'' Roses'),
						(N'Steely Dan'),
						(N'Outkast'),
						(N'James Brown'),
						(N'John Coltrane'),
						(N'Jay-Z'),
						(N'Kate Bush'),
						(N'Alanis Morissette'),
						(N'N.W.A'),
						(N'Bob Marley and the Wailers'),
						(N'Neil Young'),
						(N'My Bloody Valentine'),
						(N'Kanye West'),
						(N'Aretha Franklin'),
						(N'Curtis Mayfield'),
						(N'The Who'),
						(N'Elvis Presley'),
						(N'Frank Ocean'),
						(N'Sex Pistols'),
						(N'Beyoncé'),
						(N'Sly and the Family Stone'),
						(N'Dusty Springfield'),
						(N'AC/DC'),
						(N'John Lennon'),
						(N'The Doors'),
						(N'Miles Davis'),
						(N'David Bowie'),
						(N'Erykah Badu'),
						(N'Neil Young'),
						(N'Bruce Springsteen'),
						(N'The Jimi Hendrix Experience'),
						(N'Missy Elliott'),
						(N'The Stooges'),
						(N'Drake'),
						(N'R.E.M.'),
						(N'Metallica'),
						(N'Lucinda Williams'),
						(N'Taylor Swift'),
						(N'The Band'),
						(N'Led Zeppelin'),
						(N'The Clash'),
						(N'De La Soul'),
						(N'The Rolling Stones'),
						(N'The Allman Brothers Band'),
						(N'Hole'),
						(N'Television'),
						(N'Fiona Apple'),
						(N'Lou Reed'),
						(N'Joni Mitchell'),
						(N'Janet Jackson'),
						(N'Elton John'),
						(N'The Smiths'),
						(N'The Strokes'),
						(N'Kendrick Lamar'),
						(N'The Cure'),
						(N'Kanye West'),
						(N'Eagles'),
						(N'Sly and the Family Stone'),
						(N'Van Morrison'),
						(N'Elvis Costello'),
						(N'Nine Inch Nails'),
						(N'Led Zeppelin'),
						(N'U2'),
						(N'Beastie Boys'),
						(N'Mary J. Blige'),
						(N'Ray Charles'),
						(N'Queen'),
						(N'Pink Floyd'),
						(N'Prince'),
						(N'Portishead'),
						(N'Hank Williams'),
						(N'Joni Mitchell'),
						(N'Fugees'),
						(N'U2'),
						(N'Funkadelic'),
						(N'Adele'),
						(N'Madonna'),
						(N'Black Sabbath'),
						(N'Bob Marley and the Wailers'),
						(N'Pixies'),
						(N'Bruce Springsteen'),
						(N'The Velvet Underground'),
						(N'Led Zeppelin'),
						(N'Eminem'),
						(N'Blondie'),
						(N'Jeff Buckley'),
						(N'Frank Ocean'),
						(N'John Prine'),
						(N'Bruce Springsteen'),
						(N'George Michael'),
						(N'The Pretenders'),
						(N'PJ Harvey'),
						(N'Aretha Franklin'),
						(N'Jay-Z'),
						(N'The Replacements'),
						(N'Oasis'),
						(N'Erykah Badu'),
						(N'The Police'),
						(N'Pearl Jam'),
						(N'Crosby, Stills & Nash'),
						(N'Pulp'),
						(N'Various artists'),
						(N'Johnny Cash'),
						(N'R.E.M.'),
						(N'Buddy Holly'),
						(N'Depeche Mode'),
						(N'Steely Dan'),
						(N'Billy Joel'),
						(N'Cream'),
						(N'Sonic Youth'),
						(N'Simon & Garfunkel'),
						(N'Nirvana'),
						(N'Various artists'),
						(N'Kendrick Lamar'),
						(N'Public Enemy'),
						(N'Rod Stewart'),
						(N'Otis Redding'),
						(N'The Notorious B.I.G.'),
						(N'Love'),
						(N'Bob Dylan'),
						(N'James Taylor'),
						(N'D''Angelo'),
						(N'Cyndi Lauper'),
						(N'The Rolling Stones'),
						(N'Red Hot Chili Peppers'),
						(N'Ice Cube'),
						(N'T. Rex'),
						(N'Sleater-Kinney'),
						(N'The Who'),
						(N'Etta James'),
						(N'Beastie Boys'),
						(N'Creedence Clearwater Revival'),
						(N'Michael Jackson'),
						(N'Leonard Cohen'),
						(N'Robyn'),
						(N'The Beatles'),
						(N'The B-52''s'),
						(N'Pavement'),
						(N'Sade'),
						(N'A Tribe Called Quest'),
						(N'Björk'),
						(N'Nick Drake'),
						(N'Kanye West'),
						(N'Cat Stevens'),
						(N'David Bowie'),
						(N'Eagles'),
						(N'Lil Wayne'),
						(N'Run-DMC'),
						(N'Ray Charles'),
						(N'Joy Division'),
						(N'Nina Simone'),
						(N'Fiona Apple'),
						(N'Tom Petty'),
						(N'Grateful Dead'),
						(N'Elliott Smith'),
						(N'Oasis'),
						(N'TLC'),
						(N'Raekwon'),
						(N'Crosby, Stills, Nash & Young'),
						(N'Rage Against the Machine'),
						(N'Madonna'),
						(N'John Lennon'),
						(N'Dixie Chicks'),
						(N'Wilco'),
						(N'Derek and the Dominos'),
						(N'Little Richard'),
						(N'De La Soul'),
						(N'Patsy Cline'),
						(N'Rihanna'),
						(N'Tom Petty and the Heartbreakers'),
						(N'John Coltrane'),
						(N'Tori Amos'),
						(N'Black Sabbath'),
						(N'Metallica'),
						(N'Daft Punk'),
						(N'Willie Nelson'),
						(N'Kraftwerk'),
						(N'Boogie Down Productions'),
						(N'Sam Cooke'),
						(N'Massive Attack'),
						(N'The Velvet Underground'),
						(N'The Zombies'),
						(N'Kanye West'),
						(N'Cocteau Twins'),
						(N'LL Cool J'),
						(N'Sade'),
						(N'Green Day'),
						(N'Whitney Houston'),
						(N'Buzzcocks'),
						(N'Elton John'),
						(N'Devo'),
						(N'Pink Floyd'),
						(N'Herbie Hancock'),
						(N'Bob Dylan'),
						(N'Tracy Chapman'),
						(N'Dolly Parton'),
						(N'Joni Mitchell'),
						(N'Janis Joplin'),
						(N'The Slits'),
						(N'Beastie Boys'),
						(N'New Order'),
						(N'The Beatles'),
						(N'Pink Floyd'),
						(N'Pavement'),
						(N'The Beatles'),
						(N'Minutemen'),
						(N'Randy Newman'),
						(N'Kanye West'),
						(N'Kacey Musgraves'),
						(N'Mary J. Blige'),
						(N'The Velvet Underground'),
						(N'Gang of Four'),
						(N'The Byrds'),
						(N'Curtis Mayfield'),
						(N'Radiohead'),
						(N'Alicia Keys'),
						(N'Led Zeppelin'),
						(N'Nirvana'),
						(N'50 Cent'),
						(N'Harry Nilsson'),
						(N'Frank Sinatra'),
						(N'Donna Summer'),
						(N'Merle Haggard'),
						(N'Big Star'),
						(N'Red Hot Chili Peppers'),
						(N'The Byrds'),
						(N'The Modern Lovers'),
						(N'Björk'),
						(N'Outkast'),
						(N'Destiny''s Child'),
						(N'Van Halen'),
						(N'The Breeders'),
						(N'Weezer'),
						(N'Daft Punk'),
						(N'Neil Young and Crazy Horse'),
						(N'Peter Gabriel'),
						(N'Tom Petty'),
						(N'B.B. King'),
						(N'Shania Twain'),
						(N'New York Dolls'),
						(N'Neil Young'),
						(N'ABBA'),
						(N'Bill Withers'),
						(N'Kiss'),
						(N'Al Green'),
						(N'Sam Cooke'),
						(N'Brian Eno'),
						(N'Joy Division'),
						(N'Wire'),
						(N'Neil Young'),
						(N'Solange Knowles'),
						(N'PJ Harvey'),
						(N'Aaliyah'),
						(N'Rosalía'),
						(N'The Who'),
						(N'Billie Holiday'),
						(N'Janet Jackson'),
						(N'The Stone Roses'),
						(N'X'),
						(N'Lana Del Rey'),
						(N'Elvis Presley'),
						(N'The Clash'),
						(N'Coldplay'),
						(N'Jerry Lee Lewis'),
						(N'Prince'),
						(N'The Who'),
						(N'Vampire Weekend'),
						(N'DJ Shadow'),
						(N'The Rolling Stones'),
						(N'Madonna'),
						(N'Elvis Presley'),
						(N'Bill Withers'),
						(N'Santana'),
						(N'Bob Dylan and the Band'),
						(N'Roxy Music'),
						(N'Bob Dylan'),
						(N'Brian Eno'),
						(N'Janet Jackson'),
						(N'Snoop Doggy Dogg'),
						(N'The Smashing Pumpkins'),
						(N'The Beatles'),
						(N'Sly and the Family Stone'),
						(N'Toots and the Maytals'),
						(N'Bruce Springsteen'),
						(N'Arctic Monkeys'),
						(N'GZA'),
						(N'Gillian Welch'),
						(N'MC5'),
						(N'Stevie Wonder'),
						(N'Roxy Music'),
						(N'Eminem'),
						(N'The Cars'),
						(N'X-Ray Spex'),
						(N'Black Sabbath'),
						(N'Dr. John'),
						(N'Tom Waits'),
						(N'Sonic Youth'),
						(N'Big Star'),
						(N'Funkadelic'),
						(N'My Chemical Romance'),
						(N'Luther Vandross'),
						(N'Parliament'),
						(N'Talking Heads'),
						(N'Madvillain'),
						(N'Aerosmith'),
						(N'Drake'),
						(N'George Harrison'),
						(N'Mobb Deep'),
						(N'Lil Wayne'),
						(N'The Temptations'),
						(N'Big Brother and the Holding Company'),
						(N'Isaac Hayes'),
						(N'Robert Johnson'),
						(N'Green Day'),
						(N'Neutral Milk Hotel'),
						(N'Yeah Yeah Yeahs'),
						(N'Run-DMC'),
						(N'Rush'),
						(N'Charles Mingus'),
						(N'Lynyrd Skynyrd'),
						(N'Tame Impala'),
						(N'Massive Attack'),
						(N'The Kinks'),
						(N'Ramones'),
						(N'J Dilla'),
						(N'Radiohead'),
						(N'Aretha Franklin'),
						(N'Mariah Carey'),
						(N'Pixies'),
						(N'Kelis'),
						(N'Ike & Tina Turner'),
						(N'Taylor Swift'),
						(N'Diana Ross'),
						(N'D''Angelo and the Vanguard'),
						(N'Todd Rundgren'),
						(N'Billie Eilish'),
						(N'The Raincoats'),
						(N'Brian Wilson'),
						(N'The Go-Go''s'),
						(N'Blondie'),
						(N'Fela Kuti and Africa ''70'),
						(N'Ghostface Killah'),
						(N'Anita Baker'),
						(N'Various artists'),
						(N'The Magnetic Fields'),
						(N'Neil Young'),
						(N'Motörhead'),
						(N'Grateful Dead'),
						(N'The Beach Boys'),
						(N'Bob Dylan'),
						(N'Smokey Robinson'),
						(N'Creedence Clearwater Revival'),
						(N'Chic'),
						(N'The Meters'),
						(N'The Roots'),
						(N'Ornette Coleman'),
						(N'Dire Straits'),
						(N'Eric Church'),
						(N'Earth, Wind & Fire'),
						(N'M.I.A.'),
						(N'Marvin Gaye'),
						(N'Yo La Tengo'),
						(N'Beck'),
						(N'Paul Simon'),
						(N'Lucinda Williams'),
						(N'Al Green'),
						(N'Hüsker Dü'),
						(N'Four Tops'),
						(N'Elvis Costello'),
						(N'Los Lobos'),
						(N'Usher'),
						(N'LCD Soundsystem'),
						(N'Pavement'),
						(N'Pet Shop Boys'),
						(N'2Pac'),
						(N'Primal Scream'),
						(N'Blur'),
						(N'James Brown'),
						(N'Loretta Lynn'),
						(N'Britney Spears'),
						(N'The Weeknd'),
						(N'David Bowie'),
						(N'Fiona Apple'),
						(N'Yes'),
						(N'Alice Coltrane'),
						(N'Bad Bunny'),
						(N'Otis Redding'),
						(N'The White Stripes'),
						(N'Paul McCartney and Linda McCartney'),
						(N'Roberta Flack'),
						(N'The Supremes'),
						(N'Nine Inch Nails'),
						(N'Can'),
						(N'Bo Diddley'),
						(N'Al Green'),
						(N'Sinéad O''Connor'),
						(N'Jason Isbell'),
						(N'Kid Cudi'),
						(N'Lorde'),
						(N'Bon Iver'),
						(N'The Flying Burrito Brothers'),
						(N'Laura Nyro'),
						(N'The Isley Brothers'),
						(N'King Sunny Adé'),
						(N'The Beach Boys'),
						(N'Maxwell'),
						(N'The Rolling Stones'),
						(N'Manu Chao'),
						(N'Juvenile'),
						(N'Jefferson Airplane'),
						(N'SZA'),
						(N'Daddy Yankee'),
						(N'Big Star'),
						(N'Sheryl Crow'),
						(N'Sparks'),
						(N'Howlin'' Wolf'),
						(N'The Kinks'),
						(N'Selena'),
						(N'Miranda Lambert'),
						(N'Belle and Sebastian'),
						(N'The Pharcyde'),
						(N'Muddy Waters'),
						(N'Lady Gaga'),
						(N'Richard Thompson and Linda Thompson'),
						(N'John Mayer'),
						(N'Black Flag'),
						(N'The Stooges'),
						(N'Various artists'),
						(N'Linda Ronstadt'),
						(N'Harry Styles'),
						(N'Bonnie Raitt'),
						(N'Marvin Gaye'),
						(N'The Ronettes'),
						(N'Boyz II Men'),
						(N'Shakira'),
						(N'Various artists'),
						(N'Suicide'),
						(N'Rufus featuring Chaka Khan'),
						(N'Arcade Fire')
) AN(ArtistName)
	)
MERGE MusicProject.Artist A
USING CTE ON CTE.ArtistName = A.ArtistName
WHEN NOT MATCHED THEN 
	INSERT(ArtistName)
	VALUES(CTE.ArtistName);

SELECT * 
FROM MusicProject.Artist A
ORDER BY A.ArtistName ASC;