--Inserting Wiki of Rolling Stone's top 500 albums
--https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Albums/500
/********************
* Populating Artist *
*********************/
WITH CTE(ArtistName) AS
	(
		SELECT DISTINCT AN.ArtistName
		FROM
			(
				VALUES
						(N'Marvin Gaye'),
						(N'The Beach Boys'),
						(N'Joni Mitchell'),
						(N'Stevie Wonder'),
						(N'The Beatles'),
						(N'Nirvana'),
						(N'Fleetwood Mac'),
						(N'Prince and the Revolution'),
						(N'Bob Dylan'),
						(N'Lauryn Hill'),
						(N'The Beatles'),
						(N'Michael Jackson'),
						(N'Aretha Franklin'),
						(N'The Rolling Stones'),
						(N'Public Enemy'),
						(N'The Clash'),
						(N'Kanye West'),
						(N'Bob Dylan'),
						(N'Kendrick Lamar'),
						(N'Radiohead'),
						(N'Bruce Springsteen'),
						(N'The Notorious B.I.G.'),
						(N'The Velvet Underground'),
						(N'The Beatles'),
						(N'Carole King'),
						(N'Patti Smith'),
						(N'Wu-Tang Clan'),
						(N'D''Angelo'),
						(N'The Beatles'),
						(N'The Jimi Hendrix Experience'),
						(N'Miles Davis'),
						(N'Beyoncé'),
						(N'Amy Winehouse'),
						(N'Stevie Wonder'),
						(N'The Beatles'),
						(N'Michael Jackson'),
						(N'Dr. Dre'),
						(N'Bob Dylan'),
						(N'Talking Heads'),
						(N'David Bowie'),
						(N'The Rolling Stones'),
						(N'Radiohead'),
						(N'A Tribe Called Quest'),
						(N'Nas'),
						(N'Prince'),
						(N'Paul Simon'),
						(N'Ramones'),
						(N'Bob Marley and the Wailers'),
						(N'Outkast'),
						(N'Jay-Z'),
						(N'Chuck Berry'),
						(N'David Bowie'),
						(N'The Jimi Hendrix Experience'),
						(N'James Brown'),
						(N'Pink Floyd'),
						(N'Liz Phair'),
						(N'The Band'),
						(N'Led Zeppelin'),
						(N'Stevie Wonder'),
						(N'Van Morrison'),
						(N'Eric B. & Rakim'),
						(N'Guns N'' Roses'),
						(N'Steely Dan'),
						(N'Outkast'),
						(N'James Brown'),
						(N'John Coltrane'),
						(N'Jay-Z'),
						(N'Kate Bush'),
						(N'Alanis Morissette'),
						(N'N.W.A'),
						(N'Bob Marley and the Wailers'),
						(N'Neil Young'),
						(N'My Bloody Valentine'),
						(N'Kanye West'),
						(N'Aretha Franklin'),
						(N'Curtis Mayfield'),
						(N'The Who'),
						(N'Elvis Presley'),
						(N'Frank Ocean'),
						(N'Sex Pistols'),
						(N'Beyoncé'),
						(N'Sly and the Family Stone'),
						(N'Dusty Springfield'),
						(N'AC/DC'),
						(N'John Lennon'),
						(N'The Doors'),
						(N'Miles Davis'),
						(N'David Bowie'),
						(N'Erykah Badu'),
						(N'Neil Young'),
						(N'Bruce Springsteen'),
						(N'The Jimi Hendrix Experience'),
						(N'Missy Elliott'),
						(N'The Stooges'),
						(N'Drake'),
						(N'R.E.M.'),
						(N'Metallica'),
						(N'Lucinda Williams'),
						(N'Taylor Swift'),
						(N'The Band'),
						(N'Led Zeppelin'),
						(N'The Clash'),
						(N'De La Soul'),
						(N'The Rolling Stones'),
						(N'The Allman Brothers Band'),
						(N'Hole'),
						(N'Television'),
						(N'Fiona Apple'),
						(N'Lou Reed'),
						(N'Joni Mitchell'),
						(N'Janet Jackson'),
						(N'Elton John'),
						(N'The Smiths'),
						(N'The Strokes'),
						(N'Kendrick Lamar'),
						(N'The Cure'),
						(N'Kanye West'),
						(N'Eagles'),
						(N'Sly and the Family Stone'),
						(N'Van Morrison'),
						(N'Elvis Costello'),
						(N'Nine Inch Nails'),
						(N'Led Zeppelin'),
						(N'U2'),
						(N'Beastie Boys'),
						(N'Mary J. Blige'),
						(N'Ray Charles'),
						(N'Queen'),
						(N'Pink Floyd'),
						(N'Prince'),
						(N'Portishead'),
						(N'Hank Williams'),
						(N'Joni Mitchell'),
						(N'Fugees'),
						(N'U2'),
						(N'Funkadelic'),
						(N'Adele'),
						(N'Madonna'),
						(N'Black Sabbath'),
						(N'Bob Marley and the Wailers'),
						(N'Pixies'),
						(N'Bruce Springsteen'),
						(N'The Velvet Underground'),
						(N'Led Zeppelin'),
						(N'Eminem'),
						(N'Blondie'),
						(N'Jeff Buckley'),
						(N'Frank Ocean'),
						(N'John Prine'),
						(N'Bruce Springsteen'),
						(N'George Michael'),
						(N'The Pretenders'),
						(N'PJ Harvey'),
						(N'Aretha Franklin'),
						(N'Jay-Z'),
						(N'The Replacements'),
						(N'Oasis'),
						(N'Erykah Badu'),
						(N'The Police'),
						(N'Pearl Jam'),
						(N'Crosby, Stills & Nash'),
						(N'Pulp'),
						(N'Various artists'),
						(N'Johnny Cash'),
						(N'R.E.M.'),
						(N'Buddy Holly'),
						(N'Depeche Mode'),
						(N'Steely Dan'),
						(N'Billy Joel'),
						(N'Cream'),
						(N'Sonic Youth'),
						(N'Simon & Garfunkel'),
						(N'Nirvana'),
						(N'Various artists'),
						(N'Kendrick Lamar'),
						(N'Public Enemy'),
						(N'Rod Stewart'),
						(N'Otis Redding'),
						(N'The Notorious B.I.G.'),
						(N'Love'),
						(N'Bob Dylan'),
						(N'James Taylor'),
						(N'D''Angelo'),
						(N'Cyndi Lauper'),
						(N'The Rolling Stones'),
						(N'Red Hot Chili Peppers'),
						(N'Ice Cube'),
						(N'T. Rex'),
						(N'Sleater-Kinney'),
						(N'The Who'),
						(N'Etta James'),
						(N'Beastie Boys'),
						(N'Creedence Clearwater Revival'),
						(N'Michael Jackson'),
						(N'Leonard Cohen'),
						(N'Robyn'),
						(N'The Beatles'),
						(N'The B-52''s'),
						(N'Pavement'),
						(N'Sade'),
						(N'A Tribe Called Quest'),
						(N'Björk'),
						(N'Nick Drake'),
						(N'Kanye West'),
						(N'Cat Stevens'),
						(N'David Bowie'),
						(N'Eagles'),
						(N'Lil Wayne'),
						(N'Run-DMC'),
						(N'Ray Charles'),
						(N'Joy Division'),
						(N'Nina Simone'),
						(N'Fiona Apple'),
						(N'Tom Petty'),
						(N'Grateful Dead'),
						(N'Elliott Smith'),
						(N'Oasis'),
						(N'TLC'),
						(N'Raekwon'),
						(N'Crosby, Stills, Nash & Young'),
						(N'Rage Against the Machine'),
						(N'Madonna'),
						(N'John Lennon'),
						(N'Dixie Chicks'),
						(N'Wilco'),
						(N'Derek and the Dominos'),
						(N'Little Richard'),
						(N'De La Soul'),
						(N'Patsy Cline'),
						(N'Rihanna'),
						(N'Tom Petty and the Heartbreakers'),
						(N'John Coltrane'),
						(N'Tori Amos'),
						(N'Black Sabbath'),
						(N'Metallica'),
						(N'Daft Punk'),
						(N'Willie Nelson'),
						(N'Kraftwerk'),
						(N'Boogie Down Productions'),
						(N'Sam Cooke'),
						(N'Massive Attack'),
						(N'The Velvet Underground'),
						(N'The Zombies'),
						(N'Kanye West'),
						(N'Cocteau Twins'),
						(N'LL Cool J'),
						(N'Sade'),
						(N'Green Day'),
						(N'Whitney Houston'),
						(N'Buzzcocks'),
						(N'Elton John'),
						(N'Devo'),
						(N'Pink Floyd'),
						(N'Herbie Hancock'),
						(N'Bob Dylan'),
						(N'Tracy Chapman'),
						(N'Dolly Parton'),
						(N'Joni Mitchell'),
						(N'Janis Joplin'),
						(N'The Slits'),
						(N'Beastie Boys'),
						(N'New Order'),
						(N'The Beatles'),
						(N'Pink Floyd'),
						(N'Pavement'),
						(N'The Beatles'),
						(N'Minutemen'),
						(N'Randy Newman'),
						(N'Kanye West'),
						(N'Kacey Musgraves'),
						(N'Mary J. Blige'),
						(N'The Velvet Underground'),
						(N'Gang of Four'),
						(N'The Byrds'),
						(N'Curtis Mayfield'),
						(N'Radiohead'),
						(N'Alicia Keys'),
						(N'Led Zeppelin'),
						(N'Nirvana'),
						(N'50 Cent'),
						(N'Harry Nilsson'),
						(N'Frank Sinatra'),
						(N'Donna Summer'),
						(N'Merle Haggard'),
						(N'Big Star'),
						(N'Red Hot Chili Peppers'),
						(N'The Byrds'),
						(N'The Modern Lovers'),
						(N'Björk'),
						(N'Outkast'),
						(N'Destiny''s Child'),
						(N'Van Halen'),
						(N'The Breeders'),
						(N'Weezer'),
						(N'Daft Punk'),
						(N'Neil Young and Crazy Horse'),
						(N'Peter Gabriel'),
						(N'Tom Petty'),
						(N'B.B. King'),
						(N'Shania Twain'),
						(N'New York Dolls'),
						(N'Neil Young'),
						(N'ABBA'),
						(N'Bill Withers'),
						(N'Kiss'),
						(N'Al Green'),
						(N'Sam Cooke'),
						(N'Brian Eno'),
						(N'Joy Division'),
						(N'Wire'),
						(N'Neil Young'),
						(N'Solange Knowles'),
						(N'PJ Harvey'),
						(N'Aaliyah'),
						(N'Rosalía'),
						(N'The Who'),
						(N'Billie Holiday'),
						(N'Janet Jackson'),
						(N'The Stone Roses'),
						(N'X'),
						(N'Lana Del Rey'),
						(N'Elvis Presley'),
						(N'The Clash'),
						(N'Coldplay'),
						(N'Jerry Lee Lewis'),
						(N'Prince'),
						(N'The Who'),
						(N'Vampire Weekend'),
						(N'DJ Shadow'),
						(N'The Rolling Stones'),
						(N'Madonna'),
						(N'Elvis Presley'),
						(N'Bill Withers'),
						(N'Santana'),
						(N'Bob Dylan and the Band'),
						(N'Roxy Music'),
						(N'Bob Dylan'),
						(N'Brian Eno'),
						(N'Janet Jackson'),
						(N'Snoop Doggy Dogg'),
						(N'The Smashing Pumpkins'),
						(N'The Beatles'),
						(N'Sly and the Family Stone'),
						(N'Toots and the Maytals'),
						(N'Bruce Springsteen'),
						(N'Arctic Monkeys'),
						(N'GZA'),
						(N'Gillian Welch'),
						(N'MC5'),
						(N'Stevie Wonder'),
						(N'Roxy Music'),
						(N'Eminem'),
						(N'The Cars'),
						(N'X-Ray Spex'),
						(N'Black Sabbath'),
						(N'Dr. John'),
						(N'Tom Waits'),
						(N'Sonic Youth'),
						(N'Big Star'),
						(N'Funkadelic'),
						(N'My Chemical Romance'),
						(N'Luther Vandross'),
						(N'Parliament'),
						(N'Talking Heads'),
						(N'Madvillain'),
						(N'Aerosmith'),
						(N'Drake'),
						(N'George Harrison'),
						(N'Mobb Deep'),
						(N'Lil Wayne'),
						(N'The Temptations'),
						(N'Big Brother and the Holding Company'),
						(N'Isaac Hayes'),
						(N'Robert Johnson'),
						(N'Green Day'),
						(N'Neutral Milk Hotel'),
						(N'Yeah Yeah Yeahs'),
						(N'Run-DMC'),
						(N'Rush'),
						(N'Charles Mingus'),
						(N'Lynyrd Skynyrd'),
						(N'Tame Impala'),
						(N'Massive Attack'),
						(N'The Kinks'),
						(N'Ramones'),
						(N'J Dilla'),
						(N'Radiohead'),
						(N'Aretha Franklin'),
						(N'Mariah Carey'),
						(N'Pixies'),
						(N'Kelis'),
						(N'Ike & Tina Turner'),
						(N'Taylor Swift'),
						(N'Diana Ross'),
						(N'D''Angelo and the Vanguard'),
						(N'Todd Rundgren'),
						(N'Billie Eilish'),
						(N'The Raincoats'),
						(N'Brian Wilson'),
						(N'The Go-Go''s'),
						(N'Blondie'),
						(N'Fela Kuti and Africa ''70'),
						(N'Ghostface Killah'),
						(N'Anita Baker'),
						(N'Various artists'),
						(N'The Magnetic Fields'),
						(N'Neil Young'),
						(N'Motörhead'),
						(N'Grateful Dead'),
						(N'The Beach Boys'),
						(N'Bob Dylan'),
						(N'Smokey Robinson'),
						(N'Creedence Clearwater Revival'),
						(N'Chic'),
						(N'The Meters'),
						(N'The Roots'),
						(N'Ornette Coleman'),
						(N'Dire Straits'),
						(N'Eric Church'),
						(N'Earth, Wind & Fire'),
						(N'M.I.A.'),
						(N'Marvin Gaye'),
						(N'Yo La Tengo'),
						(N'Beck'),
						(N'Paul Simon'),
						(N'Lucinda Williams'),
						(N'Al Green'),
						(N'Hüsker Dü'),
						(N'Four Tops'),
						(N'Elvis Costello'),
						(N'Los Lobos'),
						(N'Usher'),
						(N'LCD Soundsystem'),
						(N'Pavement'),
						(N'Pet Shop Boys'),
						(N'2Pac'),
						(N'Primal Scream'),
						(N'Blur'),
						(N'James Brown'),
						(N'Loretta Lynn'),
						(N'Britney Spears'),
						(N'The Weeknd'),
						(N'David Bowie'),
						(N'Fiona Apple'),
						(N'Yes'),
						(N'Alice Coltrane'),
						(N'Bad Bunny'),
						(N'Otis Redding'),
						(N'The White Stripes'),
						(N'Paul McCartney and Linda McCartney'),
						(N'Roberta Flack'),
						(N'The Supremes'),
						(N'Nine Inch Nails'),
						(N'Can'),
						(N'Bo Diddley'),
						(N'Al Green'),
						(N'Sinéad O''Connor'),
						(N'Jason Isbell'),
						(N'Kid Cudi'),
						(N'Lorde'),
						(N'Bon Iver'),
						(N'The Flying Burrito Brothers'),
						(N'Laura Nyro'),
						(N'The Isley Brothers'),
						(N'King Sunny Adé'),
						(N'The Beach Boys'),
						(N'Maxwell'),
						(N'The Rolling Stones'),
						(N'Manu Chao'),
						(N'Juvenile'),
						(N'Jefferson Airplane'),
						(N'SZA'),
						(N'Daddy Yankee'),
						(N'Big Star'),
						(N'Sheryl Crow'),
						(N'Sparks'),
						(N'Howlin'' Wolf'),
						(N'The Kinks'),
						(N'Selena'),
						(N'Miranda Lambert'),
						(N'Belle and Sebastian'),
						(N'The Pharcyde'),
						(N'Muddy Waters'),
						(N'Lady Gaga'),
						(N'Richard Thompson and Linda Thompson'),
						(N'John Mayer'),
						(N'Black Flag'),
						(N'The Stooges'),
						(N'Various artists'),
						(N'Linda Ronstadt'),
						(N'Harry Styles'),
						(N'Bonnie Raitt'),
						(N'Marvin Gaye'),
						(N'The Ronettes'),
						(N'Boyz II Men'),
						(N'Shakira'),
						(N'Various artists'),
						(N'Suicide'),
						(N'Rufus featuring Chaka Khan'),
						(N'Arcade Fire')
				) AN(ArtistName)
	)
MERGE MusicProject.Artist A
USING CTE ON CTE.ArtistName = A.ArtistName
WHEN NOT MATCHED THEN 
	INSERT(ArtistName)
	VALUES(CTE.ArtistName);
SELECT * 
FROM MusicProject.Artist A
ORDER BY A.ArtistName ASC;


/****************************
* Populating Certification  *
*****************************/
INSERT MusicProject.Certification(CertificationName)
VALUES 
	(N'Gold'),
	(N'Platinum'),
	(N'Multi-Platinum'),
	(N'Diamond'),
	(N'None')
SELECT *
FROM MusicProject.Certification;


/****************************
* Populating RecordLabel    *
*****************************/
WITH CTE(RecordLabelName, DateFounded, DateClosed, RecordLabelLocation) AS
	(
		SELECT DISTINCT R.RecordLabelName, DateFounded, DateClosed, RecordLabelLocation
		FROM
			(
			VALUES
				(N'Eu Limited', N'1925', N'1930', N'Western Cape'),
				(N'Justo Institute', N'1909', N'1919', N'Volgograd Oblast'),
				(N'Erat Associates', N'1921', N'1995', N'Viken'),
				(N'Quisque Tincidunt Inc.', N'1933', N'', N'BolÃ­var'),
				(N'Sed Malesuada Inc.', N'1916', N'', N'Australian Capital Territory'),
				(N'Facilisi Sed Associates', N'1927', N'', N'Alajuela'),
				(N'At Fringilla Ltd', N'2000', N'', N'ThÃ¡i BÃ¬nh'),
				(N'Vivamus Associates', N'2013', N'', N'Å‚Ã³dzkie'),
				(N'Ut Sagittis Lobortis LLP', N'1991', N'', N'Davao Region'),
				(N'Litora Torquent Per LLC', N'1910', N'', N'Benue'),
				(N'Nibh Enim Incorporated', N'1948', N'', N'Rivne oblast'),
				(N'Ac Metus Incorporated', N'1920', N'2010', N'Umbria'),
				(N'Pellentesque Tincidunt Corp.', N'1983', N'1976', N'Mecklenburg-Vorpommern'),
				(N'Tellus Non Associates', N'1925', N'', N'Nottinghamshire'),
				(N'Metus Consulting', N'1994', N'', N'Jammu and Kashmir'),
				(N'Curabitur Vel Limited', N'1915', N'', N'HuÃ¡dÅng'),
				(N'Euismod Enim LLC', N'1937', N'', N'North-East Region'),
				(N'Amet LLC', N'2009', N'1980', N'Lubuskie'),
				(N'Ut Molestie PC', N'1966', N'1933', N'Valle del Cauca'),
				(N'Accumsan PC', N'1907', N'1940', N'North Region'),
				(N'Cursus Associates', N'1996', N'', N'British Columbia'),
				(N'Amet Corporation', N'1920', N'1957', N'Gilgit Baltistan'),
				(N'Enim Commodo Corp.', N'1920', N'1978', N'Kujawsko-pomorskie'),
				(N'Imperdiet Company', N'1969', N'1965', N'XÄ«nÃ¡n'),
				(N'Ligula Eu Enim Foundation', N'1940', N'1936', N'Lagos'),
				(N'Maecenas Iaculis Foundation', N'1904', N'1969', N'Podkarpackie'),
				(N'Mauris Company', N'1946', N'', N'Burgenland'),
				(N'Varius Orci Incorporated', N'1960', N'2010', N'Dalarnas lÃ¤n'),
				(N'Ac LLC', N'1929', N'1949', N'Guanacaste'),
				(N'Dapibus Quam Quis PC', N'1924', N'1969', N'Central Region'),
				(N'Tincidunt Aliquam Inc.', N'1978', N'1900', N'Ceuta'),
				(N'Felis Eget Associates', N'1997', N'1985', N'Heredia'),
				(N'Massa Quisque LLC', N'2001', N'1952', N'Lubelskie'),
				(N'Pede Nunc LLP', N'1999', N'', N'East Region'),
				(N'Eu Dui Cum Corporation', N'1947', N'1990', N'National Capital Region'),
				(N'Ullamcorper LLP', N'1950', N'1948', N'Saskatchewan'),
				(N'Vitaey Erat Incorporated', N'1907', N'1925', N'Háº£i PhÃ²ng'),
				(N'Laoreet Limited', N'1939', N'1939', N'Wielkopolskie'),
				(N'Adipiscing Elit Foundation', N'2004', N'1948', N'Mpumalanga'),
				(N'Non Nisi Limited', N'1938', N'2006', N'XÄ«bÄ›i'),
				(N'Magnis Dis Parturient Consulting', N'1961', N'', N'Friesland'),
				(N'Neque Consulting', N'1934', N'1948', N'Victoria'),
				(N'Vitaeo Industries', N'2005', N'1975', N'Hessen'),
				(N'Sed Nulla Limited', N'1952', N'1983', N'Kyiv oblast'),
				(N'Integer Sem Elit Corp.', N'1972', N'1988', N'Rogaland'),
				(N'Ut Sagittis Lobortis Corp.', N'2018', N'', N'Corse'),
				(N'Ipsum Phasellus Corp.', N'2006', N'1987', N'Marche'),
				(N'Venenatis A LLC', N'1958', N'1958', N'YÃªn BÃ¡i'),
				(N'Ultrices Posuere Cubilia Inc.', N'1999', N'2002', N'Poltava oblast'),
				(N'In Inc.', N'1931', N'', N'Madrid'),
				(N'At Auctor Incorporated', N'2001', N'2021', N'Connacht'),
				(N'Magna Et Institute', N'1978', N'1982', N'Lombardia'),
				(N'Est Tempor Corp.', N'1965', N'2006', N'Kano'),
				(N'Cubilia PC', N'1973', N'', N'Catalunya'),
				(N'Tellus Phasellus Elit PC', N'1918', N'', N'Vichada'),
				(N'Enim Nec PC', N'1996', N'', N'GuainÃ­a'),
				(N'Amet Consectetuer Consulting', N'1914', N'', N'ZhÅngnÃ¡n'),
				(N'Dictum Eu Limited', N'1971', N'', N'Tver Oblast'),
				(N'Id Enim LLP', N'1950', N'', N'Ontario'),
				(N'Neque Morbi Quis Inc.', N'1940', N'', N'Queensland'),
				(N'Lacus Quisque Purus Institute', N'1983', N'', N'West Papua'),
				(N'Pretium Corp.', N'2015', N'', N'Sinaloa'),
				(N'Egestas Incorporated', N'1977', N'', N'Istanbul'),
				(N'Magna Ltd', N'1971', N'', N'Waals-Brabant'),
				(N'Bibendum Donec Felis Ltd', N'1954', N'1973', N'Munster'),
				(N'Ultrices LLC', N'2005', N'1901', N'Heredia'),
				(N'Egestas Sed Pharetra Industries', N'2011', N'1911', N'Alajuela'),
				(N'Mattis Ltd', N'1979', N'1960', N'Mersin'),
				(N'Lorem Fringilla Foundation', N'1982', N'2010', N'Yukon'),
				(N'Metus Vitae Velit Corporation', N'1902', N'1901', N'Coquimbo'),
				(N'North Vitae Industries', N'1949', N'', N'North Island'),
				(N'Nam Consequat Institute', N'1926', N'', N'Aberdeenshire'),
				(N'Nullam Velit Dui Corp.', N'1967', N'1920', N'Waals-Brabant'),
				(N'Etiam Gravida PC', N'2006', N'', N'Veracruz'),
				(N'Enim Incorporated', N'1914', N'1935', N'North Region'),
				(N'Non Associates', N'2022', N'1908', N'Canarias'),
				(N'Mollis Corporation', N'1971', N'1953', N'Ontario'),
				(N'Facilisi Sed Ltd', N'1997', N'1988', N'Vinnytsia oblast'),
				(N'Quamio Foundation', N'1911', N'2011', N'Wyoming'),
				(N'Viverra Donec Tempus Corp.', N'1908', N'2017', N'DÅngbÄ›i'),
				(N'Cras Interdum Ltd', N'1956', N'2000', N'Amazonas'),
				(N'Et Arcu PC', N'1993', N'1920', N'Denbighshire'),
				(N'Vestibulum Ante Inc.', N'1978', N'2001', N'Stockholms lÃ¤n'),
				(N'Tellus Consulting', N'1951', N'1905', N'Sicilia'),
				(N'Aliquam Tincidunt Institute', N'2006', N'', N'Vestfold og Telemark'),
				(N'Lectus Pede Ultrices Ltd', N'1972', N'', N'GoiÃ¡s'),
				(N'Eget Incorporated', N'1973', N'1915', N'Tyrol'),
				(N'Ipsum Nunc Associates', N'1900', N'', N'Mykolaiv oblast'),
				(N'A Scelerisque Sed Limited', N'1988', N'1981', N'ÅžanlÄ±urfa'),
				(N'Metus In Lorem Inc.', N'1967', N'1916', N'JÃ¶nkÃ¶pings lÃ¤n'),
				(N'Egestas Aliquam Institute', N'1907', N'1921', N'Bursa'),
				(N'Eget Massa Suspendisse Ltd', N'1980', N'1977', N'BalÄ±kesir'),
				(N'A Limited', N'1974', N'1902', N'Heredia'),
				(N'Aliquet Incorporated', N'2001', N'1920', N'Lambayeque'),
				(N'Molestie Sed Id LLC', N'1989', N'1958', N'Ulster'),
				(N'Libero Integer Limited', N'2001', N'1905', N'Jeju'),
				(N'Natoque Ltd', N'1925', N'1960', N'Chernihiv oblast'),
				(N'Velit Eget Laoreet Inc.', N'2010', N'1944', N'East Lothian'),
				(N'Nisi Dictum LLC', N'1906', N'1906', N'Sokoto'),
				(N'Aenean Euismod Foundation', N'1998', N'', N'Virginia'),
				(N'Integer Vulputate Risus Associates', N'1995', N'1971', N'North Chungcheong'),
				(N'Odio Tristique LLP', N'1959', N'', N'Háº­u Giang'),
				(N'Enim Non Nisi LLC', N'1921', N'2019', N'Quebec'),
				(N'Id Ante Dictum Associates', N'1917', N'1985', N'Dalarnas lÃ¤n'),
				(N'Morbi Tristique Company', N'2002', N'2007', N'Salzburg'),
				(N'Euismod Ac Fermentum Foundation', N'1979', N'', N'Bursa'),
				(N'Natoque LLC', N'1990', N'', N'KwaZulu-Natal'),
				(N'Vehicula Et Rutrum Ltd', N'1905', N'', N'Emilia-Romagna'),
				(N'In Tempus Industries', N'1967', N'', N'Tennessee'),
				(N'Accumsan Sed Incorporated', N'1953', N'', N'Comunitat Valenciana'),
				(N'Viverra Donec Tempus Corporation', N'1920', N'', N'Berlin'),
				(N'Mauris LLC', N'1955', N'', N'Saarland'),
				(N'Mi Tempor LLC', N'1958', N'1961', N'Ankara'),
				(N'Lorem Ipsum Industries', N'1955', N'1998', N'Cordillera Administrative Region'),
				(N'Egestas Blandit Nam Inc.', N'1986', N'1941', N'JÃ¶nkÃ¶pings lÃ¤n'),
				(N'Pharetra Nibh Corporation', N'1902', N'1973', N'Luhansk oblast'),
				(N'Sem Egestas Blandit Foundation', N'2019', N'1926', N'Cantabria'),
				(N'Sed Diam Inc.', N'1936', N'1915', N'Opolskie'),
				(N'Auctor Vitae Industries', N'1997', N'', N'HuÃ¡dÅng'),
				(N'Semper Erat Consulting', N'2006', N'1921', N'FATA'),
				(N'Velit Aliquam Nisl Institute', N'1989', N'', N'Northern Territory'),
				(N'Luctus Vulputate Nisi Inc.', N'1928', N'', N'East Java'),
				(N'Pede Cum Sociis PC', N'1979', N'', N'Atacama'),
				(N'Cum Sociis Natoque Ltd', N'1929', N'', N'FATA'),
				(N'Viverra Institute', N'1966', N'', N'Saskatchewan'),
				(N'Cursus Diam At LLP', N'1995', N'', N'Antwerpen'),
				(N'Orci In Corporation', N'2002', N'', N'North Chungcheong'),
				(N'Suspendisse Aliquet Associates', N'1931', N'', N'Illinois'),
				(N'Cursus Vestibulum Incorporated', N'1974', N'1963', N'SÆ¡n La'),
				(N'A Purus Duis LLC', N'1920', N'1959', N'Leinster'),
				(N'Donec Vitae Erat Associates', N'1994', N'1979', N'Champagne-Ardenne'),
				(N'Placerat Augue Corp.', N'1907', N'1942', N'TarapacÃ¡'),
				(N'Congue Elit Sed Foundation', N'1967', N'1982', N'Abruzzo'),
				(N'Sagittis PC', N'1943', N'', N'ÅžanlÄ±urfa'),
				(N'Id Magna Et Associates', N'2018', N'1987', N'Inverness-shire'),
				(N'Metus Vitae Velit Corp.', N'2006', N'', N'Georgia'),
				(N'Ut Nisi A Industries', N'1954', N'1935', N'Ryazan Oblast'),
				(N'Vulputate Incorporated', N'1901', N'1945', N'Puebla'),
				(N'Nunc Ullamcorper Company', N'1946', N'1980', N'GÃ¤vleborgs lÃ¤n'),
				(N'Ornare Elit Limited', N'1992', N'', N'CÃ  Mau'),
				(N'Sem Consulting', N'1989', N'2014', N'North Island'),
				(N'Dictum Phasellus LLC', N'1938', N'1954', N'Basilicata'),
				(N'Dapibus PC', N'1979', N'1913', N'Luxemburg'),
				(N'Venenatis A Magna Company', N'1966', N'', N'Minas Gerais'),
				(N'Varius Orci LLC', N'1970', N'1944', N'Sverdlovsk Oblast'),
				(N'Velit Egestas Institute', N'1928', N'1977', N'Tyrol'),
				(N'Vitae Aliquam Inc.', N'1956', N'', N'Zhytomyr oblast'),
				(N'Faucibus Ut Nulla Ltd', N'2013', N'1927', N'Balochistan'),
				(N'Purus Corporation', N'1950', N'', N'Konya'),
				(N'Vel Pede Blandit Associates', N'1966', N'', N'Chihuahua'),
				(N'Orci Corporation', N'1909', N'', N'Chelyabinsk Oblast'),
				(N'Leo Elementum Industries', N'2017', N'', N'Luxemburg'),
				(N'Egestas Aliquam LLC', N'1970', N'', N'Gujarat'),
				(N'Massa Non Corp.', N'1974', N'', N'Free State'),
				(N'Luctus Lobortis Class PC', N'1991', N'', N'North Island'),
				(N'Nec Limited', N'2016', N'', N'Gaziantep'),
				(N'Aenean Egestas Foundation', N'1983', N'', N'Brecknockshire'),
				(N'Et Corporation', N'1984', N'', N'Cordillera Administrative Region'),
				(N'Lorem Vitae Incorporated', N'1979', N'', N'O''Higgins'),
				(N'Mauris Morbi Limited', N'1931', N'', N'MÃ¸re og Romsdal'),
				(N'Taciti Foundation', N'1960', N'', N'Central Region'),
				(N'Egestas A Scelerisque Limited', N'1970', N'', N'Saarland'),
				(N'Lectus Pede LLC', N'1952', N'', N'SlÄ…skie'),
				(N'Pharetra Felis Associates', N'1947', N'', N'GuainÃ­a'),
				(N'Arcu Vel Quam LLC', N'1912', N'', N'Southwestern Tagalog Region'),
				(N'Et Risus Incorporated', N'1961', N'', N'New South Wales'),
				(N'Venenatis Vel LLC', N'1955', N'', N'New Brunswick'),
				(N'Nec Urna Suscipit Foundation', N'2006', N'', N'Leinster'),
				(N'Magnis Dis Institute', N'1964', N'', N'Cundinamarca'),
				(N'Magna A Neque Industries', N'1991', N'', N'North Chungcheong'),
				(N'Ornare In Corp.', N'2016', N'', N'Oaxaca'),
				(N'Fusce Mollis Duis Corp.', N'2020', N'', N'Kogi'),
				(N'Amet Consectetuer Adipiscing LLP', N'1950', N'', N'Manitoba'),
				(N'Adipiscing Lobortis LLP', N'1915', N'', N'Kincardineshire'),
				(N'Fermentum Vel Foundation', N'1977', N'', N'Florida'),
				(N'Sit Amet Ante Incorporated', N'1951', N'', N'Hessen'),
				(N'Eu Corporation', N'1973', N'', N'Zakarpattia oblast'),
				(N'Lacus Quisque Imperdiet Ltd', N'1944', N'', N'Waals-Brabant'),
				(N'Sed Facilisis Industries', N'1949', N'', N'Vestland'),
				(N'Felis Eget Ltd', N'1975', N'1950', N'TrÃ¸ndelag'),
				(N'Aliquet Phasellus Industries', N'2006', N'1995', N'Florida'),
				(N'Arcu Aliquam Company', N'1910', N'', N'Utah'),
				(N'Nulla Industries', N'1992', N'', N'Nuevo LeÃ³n'),
				(N'Ante Institute', N'1916', N'', N'Bicol Region'),
				(N'Diam Lorem Industries', N'2001', N'', N'ParaÃ­ba'),
				(N'Vestibulum Accumsan PC', N'2021', N'1967', N'Smolensk Oblast'),
				(N'Lacus Ltd', N'1974', N'1913', N'Zaporizhzhia oblast'),
				(N'Maecenas Mi Inc.', N'2005', N'1901', N'North-East Region'),
				(N'Amet Ornare Corp.', N'1910', N'2020', N'XÄ«nÃ¡n'),
				(N'Nisi Magna Associates', N'1934', N'1989', N'Munster'),
				(N'Libero Dui Associates', N'2009', N'1986', N'Gilgit Baltistan'),
				(N'Ante Incorporated', N'1936', N'1971', N'West Sumatra'),
				(N'Proin Vel Consulting', N'1956', N'', N'Sicilia'),
				(N'Pharetra Nam Corporation', N'1976', N'', N'Lambayeque'),
				(N'Hendrerit Corp.', N'1949', N'1926', N'Gyeonggi'),
				(N'Eua Limited', N'1994', N'1923', N'North Chungcheong'),
				(N'Nunc Institute', N'1992', N'', N'Ulster'),
				(N'EuR Corporation', N'1949', N'1983', N'Northwest Territories'),
				(N'Diam Dictum Industries', N'1972', N'1912', N'Zamboanga Peninsula'),
				(N'Est Ac Company', N'1928', N'1971', N'XÄ«nÃ¡n'),
				(N'Enim Nisl Corp.', N'1984', N'', N'Magallanes y AntÃ¡rtica Chilena'),
				(N'Mollis Vitae Posuere Ltd', N'1972', N'', N'Alajuela'),
				(N'Facilisis Lorem LLC', N'1968', N'', N'Dnipropetrovsk oblast'),
				(N'Tempus Lorem Corporation', N'1992', N'', N'Nagaland'),
				(N'Ac Libero Ltd', N'2005', N'1961', N'North West'),
				(N'Arcu Ac Incorporated', N'1973', N'2002', N'Herefordshire'),
				(N'Nibh Phasellus Incorporated', N'1992', N'1981', N'Rajasthan'),
				(N'Inceptos Hymenaeos Mauris Associates', N'1992', N'', N'South Island'),
				(N'Ipsum Ac LLP', N'1995', N'2001', N'Alajuela'),
				(N'Hendrerit A Arcu PC', N'1992', N'2007', N'Oslo'),
				(N'Nibh Enim Ltd', N'2012', N'1993', N'Rostov Oblast'),
				(N'Donec Elementum Lorem LLP', N'1921', N'1977', N'Vorarlberg'),
				(N'Ut Pharetra Inc.', N'1909', N'1959', N'Arequipa'),
				(N'Elit Pellentesque Corporation', N'2013', N'2016', N'Munster'),
				(N'Lorem Ipsum Ltd', N'2018', N'', N'Prince Edward Island'),
				(N'Morbi Associates', N'2002', N'1931', N'AragÃ³n'),
				(N'Facilisis Facilisis Institute', N'1994', N'', N'Tolima'),
				(N'Nisi A Institute', N'1914', N'1913', N'ParÃ¡'),
				(N'Elit Curabitur Incorporated', N'1958', N'1969', N'Australian Capital Territory'),
				(N'Nunc Associates', N'1967', N'1906', N'Oyo'),
				(N'Iaculis LLC', N'1968', N'1905', N'Cartago'),
				(N'Rhoncus Proin Nisl Foundation', N'1957', N'1934', N'CÃ  Mau'),
				(N'Dictum Proin Industries', N'1994', N'', N'West Kalimantan'),
				(N'Tortorr Corporation', N'2012', N'1961', N'Munster'),
				(N'Litora Corporation', N'1996', N'1940', N'Veracruz'),
				(N'Arcu LLP', N'1973', N'1912', N'Mecklenburg-Vorpommern'),
				(N'Libero Est Congue PC', N'1973', N'', N'Dalarnas lÃ¤n'),
				(N'Aliquet Molestie Corporation', N'2016', N'2007', N'Uttar Pradesh'),
				(N'Iaculis Aliquet Corp.', N'1985', N'1941', N'Dalarnas lÃ¤n'),
				(N'Donec Elementum Foundation', N'1924', N'1914', N'Lambayeque'),
				(N'Orci Sem Associates', N'1999', N'1957', N'Bali'),
				(N'Gravida Mauris Ut Foundation', N'1964', N'2015', N'Special Capital Region of Jakarta'),
				(N'Dictum PC', N'1946', N'2015', N'Guaviare'),
				(N'Mauris Nulla Company', N'1983', N'1902', N'Free State'),
				(N'Gravida LLC', N'1927', N'1969', N'Zaporizhzhia oblast'),
				(N'Ligula Nullam Feugiat Limited', N'1997', N'1943', N'DÅngbÄ›i'),
				(N'Feugiat Incorporated', N'2004', N'1969', N'Special Region of Yogyakarta'),
				(N'Eu Erat Industries', N'1976', N'', N'Zuid Holland'),
				(N'Egestas Nunc Ltd', N'1919', N'1997', N'Puno'),
				(N'Eleifend Cras Inc.', N'1925', N'1988', N'Northamptonshire'),
				(N'Lectus PC', N'1990', N'1952', N'Coquimbo'),
				(N'Leo Consulting', N'2004', N'', N'West-Vlaanderen'),
				(N'Feugiat Placerat Consulting', N'1991', N'1930', N'Soccsksargen'),
				(N'Quam A Felis Institute', N'1973', N'1977', N'Báº¯c Giang'),
				(N'Eu Enim Etiam Foundation', N'1916', N'1964', N'South Island'),
				(N'Tortoron Corporation', N'2011', N'', N'Australian Capital Territory'),
				(N'Semper Dui Lectus Ltd', N'2005', N'', N'Karnataka'),
				(N'Et Magnis Dis Ltd', N'1992', N'2002', N'Bicol Region'),
				(N'Tellus Suspendisse Sed LLP', N'1925', N'1905', N'Manisa'),
				(N'Ut Associates', N'1932', N'2019', N'Oost-Vlaanderen'),
				(N'Molestie Orci Corp.', N'1926', N'1933', N'East Region'),
				(N'Sagittis Nullam LLP', N'2015', N'1961', N'Tasmania'),
				(N'Luctus Felis Purus Industries', N'1922', N'', N'Meta'),
				(N'Eu Euismod Ac LLC', N'1971', N'', N'Dnipropetrovsk oblast'),
				(N'Sapien Molestie PC', N'2015', N'', N'Salzburg'),
				(N'Ultrices Corp.', N'1936', N'', N'Heredia'),
				(N'Velit Eu Corp.', N'1956', N'', N'Maharastra'),
				(N'Fermentum Corporation', N'1931', N'', N'Angus'),
				(N'Enim LLC', N'1906', N'', N'FATA'),
				(N'Sed Turpis LLP', N'2010', N'', N'Antioquia'),
				(N'Sit Limited', N'1976', N'', N'Quáº£ng BÃ¬nh'),
				(N'Sapien Aenean LLC', N'1943', N'', N'Lower Austria'),
				(N'Facilisis Magna Industries', N'2010', N'', N'Adana'),
				(N'A Sollicitudin Limited', N'2018', N'', N'MaranhÃ£o'),
				(N'Sodales Elit Inc.', N'1957', N'', N'Limburg'),
				(N'Posuere At Velit LLP', N'1951', N'', N'ParÃ¡'),
				(N'Morbi Non Sapien LLC', N'2006', N'', N'East Nusa Tenggara'),
				(N'Euismod Corporation', N'1901', N'', N'Denbighshire'),
				(N'Sem Foundation', N'1919', N'', N'Nizhny Novgorod Oblast'),
				(N'Semper LLP', N'1992', N'', N'Australian Capital Territory'),
				(N'Cras Foundation', N'1918', N'2019', N'Upper Austria'),
				(N'Vel LLP', N'2015', N'1952', N'Munster'),
				(N'Auctor Odio Corporation', N'1935', N'1965', N'Henegouwen'),
				(N'Nunc Commodo Institute', N'2004', N'', N'Rio Grande do Sul'),
				(N'Molestie Institute', N'2001', N'1984', N'Maule'),
				(N'Odio Company', N'1992', N'1928', N'HuÃ¡bÄ›i'),
				(N'Blandit Mattis Corporation', N'2005', N'', N'Mizoram'),
				(N'Euismod Et Industries', N'1973', N'2020', N'Northamptonshire'),
				(N'Ut Pharetra Sed LLP', N'1941', N'1941', N'FATA'),
				(N'Nulla Integer Vulputate Limited', N'1977', N'1928', N'Limburg'),
				(N'Amet Massa Quisque PC', N'1963', N'2006', N'Alberta'),
				(N'Cursus Nunc Institute', N'1959', N'1966', N'North Island'),
				(N'Faucibus Ut Nulla Incorporated', N'1905', N'', N'Lampung'),
				(N'Enim Non Inc.', N'1901', N'1941', N'Arequipa'),
				(N'Consequat Purus Foundation', N'2011', N'2018', N'Tomsk Oblast'),
				(N'Nisl Sem Consulting', N'1972', N'2015', N'San Luis PotosÃ­'),
				(N'Diam PC', N'1914', N'1910', N'Podkarpackie'),
				(N'Cursus Consulting', N'1926', N'1952', N'Davao Region'),
				(N'Nulla Integer Urna Industries', N'1932', N'1906', N'Cundinamarca'),
				(N'Nunc Ullamcorper Industries', N'1933', N'1957', N'Central Region'),
				(N'Nibh Institute', N'1996', N'1904', N'Lower Austria'),
				(N'Tempus Foundation', N'2013', N'1987', N'Guanacaste'),
				(N'Ornare Libero At Corp.', N'1931', N'1990', N'Provence-Alpes-CÃ´te d''Azur'),
				(N'Rutrum Fusce Dolor PC', N'1921', N'', N'La Libertad'),
				(N'Varius Institute', N'2001', N'1979', N'VaupÃ©s'),
				(N'Nulla Donec Corporation', N'1957', N'1941', N'Santa Catarina'),
				(N'Est Corp.', N'1970', N'1995', N'Khyber Pakhtoonkhwa'),
				(N'Cras Convallis LLC', N'2002', N'2001', N'Novgorod Oblast'),
				(N'Nunc Risus Ltd', N'2008', N'1946', N'Benue'),
				(N'Ultricies LLC', N'2011', N'', N'KwaZulu-Natal'),
				(N'Non Cursus PC', N'1909', N'1969', N'Abruzzo'),
				(N'Quamnn Foundation', N'2000', N'1991', N'Washington'),
				(N'Dui Augue Limited', N'1908', N'2005', N'Lower Austria'),
				(N'Tortor Dictum Inc.', N'1958', N'1982', N'Minas Gerais'),
				(N'Sapien Cursus LLP', N'1905', N'', N'Guanajuato'),
				(N'Facilisis Suspendisse Inc.', N'1955', N'1953', N'Cartago'),
				(N'Dis Parturient Montes Consulting', N'1954', N'1964', N'Puno'),
				(N'Morbi Accumsan Industries', N'1974', N'', N'Western Australia'),
				(N'A LLC', N'1940', N'', N'Piura'),
				(N'Curabitur Ut Corp.', N'2006', N'1904', N'Dalarnas lÃ¤n'),
				(N'Sapien Ltd', N'1982', N'', N'Äá»“ng Nai'),
				(N'Feugiat Metus Industries', N'2019', N'', N'Opolskie'),
				(N'Ut PC', N'2000', N'', N'Connacht'),
				(N'Euismod Est Industries', N'1926', N'', N'Niedersachsen'),
				(N'Vel Arcu Curabitur Corp.', N'1937', N'1944', N'Lambayeque'),
				(N'Vitae Sodales PC', N'2007', N'1957', N'Adana'),
				(N'Cursus Ltd', N'1923', N'2007', N'Corse'),
				(N'Augue LLC', N'2019', N'1922', N'Connacht'),
				(N'Ornare Facilisis Consulting', N'1908', N'2010', N'Central Kalimantan'),
				(N'Quam A Felis Consulting', N'1943', N'2021', N'Hamburg'),
				(N'Amet Ultricies Foundation', N'2000', N'1958', N'Niedersachsen'),
				(N'Cras Dolor Company', N'1905', N'', N'MaÅ‚opolskie'),
				(N'Metus Vivamus Euismod LLC', N'2006', N'', N'Ternopil oblast'),
				(N'Quisque Corporation', N'2004', N'1994', N'Soccsksargen'),
				(N'Lacus Pede PC', N'1904', N'1944', N'Veracruz'),
				(N'Posuere Cubilia Curae Ltd', N'1955', N'', N'Jeju'),
				(N'Egestas Duis Ltd', N'1900', N'2019', N'Chernihiv oblast'),
				(N'Torquent Per Conubia Inc.', N'1915', N'1950', N'Maluku'),
				(N'Amet Inc.', N'1933', N'1966', N'Midi-PyrÃ©nÃ©es'),
				(N'Nunc Interdum Inc.', N'2019', N'1946', N'North-East Region'),
				(N'Augue Id Ante Company', N'1931', N'', N'SwiÄ™tokrzyskie'),
				(N'Maecenas Libero Est Inc.', N'1972', N'1974', N'North Region'),
				(N'Odio A Associates', N'2004', N'1979', N'Antwerpen'),
				(N'Aliquet Lobortis Corp.', N'1934', N'1954', N'WarmiÅ„sko-mazurskie'),
				(N'Netus Et Malesuada LLC', N'1959', N'', N'CearÃ¡'),
				(N'Quis Turpis Inc.', N'1923', N'1978', N'Connacht'),
				(N'Vitae Semper Industries', N'1959', N'', N'Western Cape'),
				(N'Interdum Corp.', N'1936', N'1927', N'Connacht'),
				(N'Quis Pede Company', N'2015', N'2019', N'Antalya'),
				(N'Tincidunt Corp.', N'1999', N'1923', N'Lambayeque'),
				(N'Lorem Semper LLP', N'1945', N'', N'JÃ¶nkÃ¶pings lÃ¤n'),
				(N'At Augue Inc.', N'1964', N'1915', N'Minas Gerais'),
				(N'Mi Tempor Ltd', N'1982', N'1915', N'Troms og Finnmark'),
				(N'Quamer Corporation', N'1953', N'1935', N'Molise'),
				(N'Vivamus Nisi Associates', N'1991', N'1963', N'Lubelskie'),
				(N'Etiam Vestibulum PC', N'1939', N'1903', N'Chiapas'),
				(N'Ac Urna Ut Associates', N'1961', N'', N'Pomorskie'),
				(N'Rutrum Urna LLC', N'1918', N'2004', N'Bursa'),
				(N'Turpis Nulla Aliquet Limited', N'1973', N'1901', N'SwiÄ™tokrzyskie'),
				(N'Augue Id Corp.', N'1950', N'1956', N'Alajuela')
		) R(RecordLabelName, DateFounded, DateClosed, RecordLabelLocation)
	)

MERGE MusicProject.RecordLabel RL
USING CTE ON CTE.RecordLabelName = RL.RecordLabelName
WHEN NOT MATCHED THEN 
	INSERT(RecordLabelName, DateFounded, DateClosed, RecordLabelLocation)
	VALUES(CTE.RecordLabelName, CTE.DateFounded, CTE.DateClosed, CTE.RecordLabelLocation);
SELECT *
FROM MusicProject.RecordLabel;


--INSERT MusicProject.Album(ArtistID, AlbumTitle, ReleaseDate, RecordLabelID, ProducerID, CertificationID)
INSERT MusicProject.Album(ArtistID, AlbumTitle, ReleaseDate, ProducerID)
SELECT Ar.ArtistID, A.AlbumTitle, ReleaseDate, RecordLabelID, ProducerID, CertificationID
FROM (
	VALUES 
		(N'Marvin Gaye', N'What''s Going On', N'1940', N'Eget Institute', N'Maxwell Davidson', N'Diamond'),
		(N'The Beach Boys', N'Pet Sounds', N'1939', N'Aliquam Arcu LLC', N'Macy Kelley', N'Gold'),
		(N'Joni Mitchell', N'Blue', N'1968', N'Per Incorporated', N'Brandon Moreno', N'None'),
		(N'Stevie Wonder', N'Songs in the Key of Life', N'1954', N'Aliquam Rutrum Lorem Corporation', N'August Donovan', N'Multi-Platinum'),
		(N'The Beatles', N'Abbey Road', N'1900', N'Egestas A Corp.', N'Lydia Park', N'Gold'),
		(N'Nirvana', N'Nevermind', N'1963', N'Porttitor Inc.', N'Dora Mcintyre', N'Platinum'),
		(N'Fleetwood Mac', N'Rumours', N'1966', N'In Scelerisque Scelerisque Corporation', N'Ocean Henry', N'Gold'),
		(N'Prince and the Revolution', N'Purple Rain', N'1958', N'Mauris Quis Corp.', N'Zoe Ramsey', N'Gold'),
		(N'Bob Dylan', N'Blood on the Tracks', N'1917', N'Eget Inc.', N'Kaitlin Rodgers', N'Gold'),
		(N'Lauryn Hill', N'The Miseducation of Lauryn Hill', N'1990', N'Ac Eleifend Institute', N'Sean Medina', N'Gold')


	) A([Name], AlbumTitle, ReleaseDate, RecordLabelName, ProducerLabelName, CertificationName)
	INNER JOIN MusicProject.Artist Ar ON Ar.ArtistName = A.[Name]
	INNER JOIN MusicProject.Certification C ON C.CertificationName = A.CertificationName

SELECT *
FROM MusicProject.Album;
SELECT *
FROM MusicProject.Artist;

INSERT MusicProject.Producer(ProducerName)
VALUES (N'ashley');

SELECT *
FROM MusicProject.Producer;